name: Build APK

on:
  push:
    branches: [ "*" ]
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false
      
      - name: Set up Signing Key
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore
          
      - name: Grant Execute Permission for gradlew
        run: chmod +x ./gradlew
      
      - name: Build with Gradle and Find APK
        id: build
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          ./gradlew assembleRelease
          echo "APK=$(find ./app/build/outputs/apk -name "*.apk")" >> $GITHUB_OUTPUT
      
      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          name: MobileGL
          path: ${{ steps.build.outputs.APK }}
          
      - name: Delete Old latest Release and Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(git tag --list latest)
          gh release delete "$LATEST_TAG" --yes || echo "No previous latest release found to delete."
          git push origin --delete "$LATEST_TAG" || echo "No previous latest tag found to delete."
          
      - name: Create latest Release
        uses: softprops/action-gh-release@v2
        with:
          name: "MobileGL Latest Plugin File"
          tag_name: "latest"
          target_commitish: ${{ github.sha }}
          body: |
            - 这是最新构建的 MobileGL 插件，将在下一次 Github Actions 运行时被替换

            - This is the newly built MobileGL plugin which will be replaced during the next Github Actions run
          files: app/build/outputs/apk/release/*.apk
